[tool.pytest.ini_options]
markers = ["slow: marks tests as slow (deselect with '-m \"not slow\"')"]

[tool.black]
line-length = 119
extend-exclude = '''
(
  .venv/
  | .venv
)
'''

[tool.flake8]
docstring-convention = "all"
ignore = ["D203", "D212"]
exclude = [".venv"]
max-line-length = 119

# radon
radon-max-cc = 10

[tool.isort]
profile = "black"
multi_line_output = "VERTICAL_HANGING_INDENT"
force_grid_wrap = 2
line_length = 119

[tool.pylint."messages control"]
disable = ["too-few-public-methods"]
max-line-length = 119


[tool.ruff]
# Enable flake8-bugbear (`B`) rules.
# Select a subset of rules to enable:
#   E: PEP 8 errors and warnings
#   F: Fatal errors (e.g. parsing/AST errors)
#   B: Bugbear rules (e.g. trying to modify an iterable while iterating)
#   ERA: `ruff` rules (e.g. `ERA001`, `ERA002`, etc.)
lint.select = ["E", "F", "B", "ERA"]

# Never enforce `E501` (line length violations).
lint.ignore = ["E501", "F401"]

# Avoid trying to fix flake8-bugbear (`B`) violations.
lint.unfixable = ["B"]
line-length = 119

# Ignore `E402` (import violations) in all `__init__.py` files, and in `path/to/file.py`.
[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402"]
"path/to/file.py" = ["E402"]
